config/routes.rb
Pmap::Application.routes.draw do

  resources :processdefs do
	  resources :steps do
		  member do
			post 'increment'
			post 'decrement'
		  end
	  end
  end

  root :to => 'processdefs#index'

end

app/models/processdef.rb
class Processdef < ActiveRecord::Base
  has_many :steps, :order => "step_order"
  attr_accessible :description, :name
end

app/models/step.rb
class Step < ActiveRecord::Base
  belongs_to :processdef
  attr_accessible :description, :lt, :name, :processdef_id, :pt, :step_order
  acts_as_list :scope => :processdef, :column => :step_order

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/processdefs_controller.rb
class ProcessdefsController < ApplicationController
  # GET /processdefs
  # GET /processdefs.json
  def index
    @processdefs = Processdef.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @processdefs }
    end
  end

  # GET /processdefs/1
  # GET /processdefs/1.json
  def show
    @processdef = Processdef.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @processdef }
    end
  end

  # GET /processdefs/new
  # GET /processdefs/new.json
  def new
    @processdef = Processdef.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @processdef }
    end
  end

  # GET /processdefs/1/edit
  def edit
    @processdef = Processdef.find(params[:id])
  end

  # POST /processdefs
  # POST /processdefs.json
  def create
    @processdef = Processdef.new(params[:processdef])

    respond_to do |format|
      if @processdef.save
        format.html { redirect_to @processdef, notice: 'Process was successfully created.' }
        format.json { render json: @processdef, status: :created, location: @processdef }
      else
        format.html { render action: "new" }
        format.json { render json: @processdef.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /processdefs/1
  # PUT /processdefs/1.json
  def update
    @processdef = Processdef.find(params[:id])

    respond_to do |format|
      if @processdef.update_attributes(params[:processdef])
        format.html { redirect_to @processdef, notice: 'Process was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @processdef.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /processdefs/1
  # DELETE /processdefs/1.json
  def destroy
    @processdef = Processdef.find(params[:id])
    @processdef.destroy

    respond_to do |format|
      format.html { redirect_to processdefs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController

  before_filter :set_processdef

  # GET /steps
  # GET /steps.json
  def index

    @steps = @processdef.steps.order(:step_order)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @steps }
    end
  end

  # GET /steps/1
  # GET /steps/1.json
  def show
    @step = Step.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @step }
    end
  end

  # GET /steps/new
  # GET /steps/new.json
  def new
    @step = @processdef.steps.build

    respond_to do |format|
	format.html
    end

  end

  # GET /steps/1/edit
  def edit
    @step = Step.find(params[:id])
  end

  # POST /steps
  # POST /steps.json
  def create

    @step = @processdef.steps.build(params[:step])

    respond_to do |format|
      if @step.save
        format.html { redirect_to processdef_steps_url(@processdef), notice: 'Step was successfully created.' }
        format.json { render json: @step, status: :created, location: @step }
      else
        format.html { render action: "new" }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /steps/1
  # PUT /steps/1.json
  def update
    @step = Step.find(params[:id])

    respond_to do |format|
      if @step.update_attributes(params[:step])
        format.html { redirect_to processdef_steps_url(@processdef), notice: 'Step was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /steps/1
  # DELETE /steps/1.json
  def destroy
    @step = Step.find(params[:id])
    @step.destroy

    respond_to do |format|
      format.html { redirect_to processdef_steps_url(@processdef) }
      format.json { head :no_content }
    end
  end

  def decrement
    @step = Step.find(params[:id])
    @step.move_higher

    respond_to do |format|
      format.html { redirect_to processdef_steps_url(@processdef) }
      format.json { head :no_content }
    end
  end


  def increment
    @step = Step.find(params[:id])
    @step.move_lower

    respond_to do |format|
      format.html { redirect_to processdef_steps_url(@processdef) }
      format.json { head :no_content }
    end
  end

  private

  def set_processdef
	  @processdef = Processdef.find(params[:processdef_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/processdefs_helper.rb
module ProcessdefsHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pmap</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div id="header">

		<h1><%= link_to "RAIO Performance Optimization Mapper", root_url %></h1>

	</div>

	<div id='notice'>
		<p id="notice"><%= notice %></p>
	</div>



	<hr/>

	<div id="content_container">

		<%= yield %>

	</div>

</body>
</html>

app/views/processdefs/_form.html.erb
<%= form_for(@processdef) do |f| %>
  <% if @processdef.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@processdef.errors.count, "error") %> prohibited this Process from being saved:</h2>

      <ul>
      <% @processdef.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit "Create Process" %>
  </div>
<% end %>

app/views/processdefs/_processdef.html.erb
  <div class="processdef_block">
    <div class="section"><b>Process: <%= processdef.name %></b></div>
    <div class="section"><%= processdef.description %></div>
    <div class="command_bar section">
	    <%= link_to 'Show', processdef_steps_path(processdef), :class => "blue_button" %> | 
	    <%= link_to 'Edit', edit_processdef_path(processdef), :class => "blue_button" %> | 
	    <%= link_to 'Delete', processdef, method: :delete, :class => "red_button", data: { confirm: 'Are you sure?' } %></div>
  </div>
  <br/>

app/views/processdefs/edit.html.erb
<h1>Editing processdef</h1>

<%= render 'form' %>

<%= link_to 'Show', @processdef %> |
<%= link_to 'Back', processdefs_path %>

app/views/processdefs/index.html.erb
<div class="title">Processes</div>
<br/>

<%= render @processdefs %>

<br />

<%= link_to 'New Process', new_processdef_path, :class => "green_button" %>

app/views/processdefs/new.html.erb
<h1>New Process</h1>

<%= render 'form' %>

<%= link_to 'Back', processdefs_path %>

app/views/processdefs/show.html.erb
<div id="processdef" class="container">

<div class="content">
	<div id="sections">
		<p class="section">
			<b>Process:</b>
			<%= @processdef.name %>
		</p>
		<p class="section">
			<%= @processdef.description %>
		</p>

	</div>
	<div class="command_bar section">
		<%= link_to 'Edit', edit_processdef_path(@processdef), :class => "blue_button" %> |
		<%= link_to 'Back', processdefs_path, :class => "blue_button" %>
	</div>


</div>


</div>

app/views/steps/_form.html.erb
	<% if @step.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@step.errors.count, "error") %> prohibited this step from being saved:</h2>

			<ul id="error_list">
				<% @step.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>


<%= form_for([@processdef, @step]) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :size => "20x5" %>
  </div>
  <div class="field">
    <%= f.label :pt %><br />
    <%= f.number_field :pt %>
  </div>
  <div class="field">
    <%= f.label :lt %><br />
    <%= f.number_field :lt %>
  </div>
  <div class="field">
    <%= f.label :step_order %><br />
    <%= f.number_field :step_order %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/steps/_step.html.erb
<div id="step<%= step.step_order %>" class="step_block" data-order="<%= step.step_order %>">
	<div class="step_order">STEP <%= step.step_order %></div>
	<div class="section step_name"><b><%= step.name %></b></div>
    	<div class="section process_time">
	    <table>
		<tr>
			<td class="label">PT:</td><td class="value"><%= step.pt %></td>
			<td class="label">LT:</td><td class="value"><%= step.lt %></td>
	    	</tr>
	</table>
    </div>
    <div class="command_bar section">
	    <%= link_to image_tag("edit.png"), edit_processdef_step_path(@processdef, step) %> &nbsp;
	    <%= link_to image_tag("delete.png"), [@processdef, step], method: :delete, data: { confirm: 'Are you sure?' } %>   &nbsp;&nbsp; 
	    <%= link_to image_tag("left.png"), decrement_processdef_step_path(@processdef, step), :method => :post %> &nbsp;
	    <%= link_to image_tag("right.png"), increment_processdef_step_path(@processdef, step), :method => :post %> &nbsp;
    </div>
  </div>
  

app/views/steps/edit.html.erb
<div class="title">Editing Step for <%= @processdef.name %></div>

<%= render 'form' %>

<%= link_to 'Show', [@processdef, @step] %> |
<%= link_to 'Back', processdef_steps_path(@processdef) %>

app/views/steps/index.html.erb
<div class="title"><%= @processdef.name %> Steps</div>
<%= link_to 'New Step', new_processdef_step_path(@processdef) %>
<br/>
<br/>

<div id="steps_view">
	<%= render @steps %>
</div>

<br />

app/views/steps/new.html.erb
<div class="title">New step for <%= @processdef.name %></div>

<%= render 'form' %>

<%= link_to 'Back', processdef_steps_path(@processdef) %>

app/views/steps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @step.name %>
</p>

<p>
  <b>Description:</b>
  <%= @step.description %>
</p>

<p>
  <b>Pt:</b>
  <%= @step.pt %>
</p>

<p>
  <b>Lt:</b>
  <%= @step.lt %>
</p>



<%= link_to 'Edit', edit_processdef_step_path(@processdef, @step) %>
<%= link_to 'Back', processdef_steps_path(@processdef) %>